/* Auto-generated by top2h.py from top_cpu_mm.rdl. Do not edit. */
#ifndef _TOP_H_
#define _TOP_H_

/* ============================================================ */
/* Top map: ErbiumCPU_MemoryMap */
/* ============================================================ */

/* Instance: System_Reg system_registers */
#define ERBIUM_TOP_SYSTEM_REGISTERS_BASE 0x02000000ul

/* Instance: axi2mram_bridge_registers mram_registers */
#define ERBIUM_TOP_MRAM_REGISTERS_BASE 0x02001000ul

/* Instance: I2C_Reg i2c_registers */
#define ERBIUM_TOP_I2C_REGISTERS_BASE 0x02002000ul

/* Instance: QSPI_Reg qspi_registers */
#define ERBIUM_TOP_QSPI_REGISTERS_BASE 0x02003000ul

/* Instance: UART_Reg uart_registers */
#define ERBIUM_TOP_UART_REGISTERS_BASE 0x02004000ul

/* Instance: memories ROMRAM */
#define ERBIUM_TOP_ROMRAM_BASE 0x02008000ul

/* Instance: external bootrom ROM */
#define ERBIUM_TOP_BOOTROM_BASE 0x02008000ul

/* Instance: external sram SRAM */
#define ERBIUM_TOP_SRAM_BASE 0x0200C000ul

/* Instance: SCCR_Reg xspi_registers */
#define ERBIUM_TOP_XSPI_REGISTERS_BASE 0x0200F000ul

/* Instance: config nic_config */
#define ERBIUM_TOP_NIC_CONFIG_BASE 0xFE000000ul

/* Instance: external ni700_registers ni700_registers */
#define ERBIUM_TOP_NI700_REGISTERS_BASE 0xFE000000ul

/* Instance: external mram mram */
#define ERBIUM_TOP_MRAM_BASE 0x40000000ul

/* Instance: Erbium_ESR cpu_registers */
#define ERBIUM_TOP_CPU_REGISTERS_BASE 0x80000000ul

/* Instance: PLIC_cpu plic */
#define ERBIUM_TOP_PLIC_BASE 0xA0000000ul

#endif /* _TOP_H_ */
